version: '3.8'
services:
  homeassistant:
    extends:
      file: docker-compose.homeassistant.yml
      service: homeassistant

  homer:
    extends:
      file: docker-compose.homer.yml
      service: homer

  nginx:
    extends:
      file: docker-compose.nginx.yml
      service: nginx

networks:
  main_network:
    driver: bridge