version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      main_network:
        ipv4_address: 172.18.0.11
