---
title: "Ninth Circle"
subtitle: "Welcome to the Ninth Circle"
logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/homer.png"
header: true

theme: dark

# Services
services:
  - name: "Automation"
    icon: "fa-solid fa-bolt"
    items:
    - name: "Home Assistant"
      logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/home-assistant-alt.png"
      subtitle: "Open source home automation that puts local control and privacy first."
      url: "http://192.168.1.126/homeassistant"
      tag: "home assistant"
      target: "_blank"
